version: "2"

services:
  nginx:
    container_name: qgisserver-perfsuite-nginx
    image: nginx:1.13
    ports:
      - 8088:80
    networks:
      - qgis
    volumes:
      - ./scenarios/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - qgis-release-3_16
      - qgis-release-3_16-parallel-rendering
      - qgis-release-3_22
      - qgis-release-3_22-parallel-rendering
      - qgis-master
      - qgis-master-parallel-rendering

  qgis-release-3_16:
    container_name: qgisserver-perfsuite-release-3_16
    image: qgisserver-perfsuite:release-3_16
    build:
      context: ./docker
      args:
        VERSION: release-3_16
    command: /cmd.sh
    networks:
      - qgis
      - data
    volumes:
      - ./data-volume:/data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=0

  qgis-release-3_16-parallel-rendering:
    container_name: qgisserver-perfsuite-release-3_16-parallel-rendering
    image: qgisserver-perfsuite:release-3_16
    build:
      context: ./docker
      args:
        VERSION: release-3_16
    command: /cmd.sh
    networks:
      - qgis
      - data
    volumes:
      - ./data-volume:/data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=1
      - QGIS_SERVER_MAX_THREADS=4

  qgis-release-3_22:
    container_name: qgisserver-perfsuite-release-3_22
    image: qgisserver-perfsuite:release-3_22
    build:
      context: ./docker
      args:
        VERSION: release-3_22
    command: /cmd.sh
    networks:
      - qgis
      - data
    volumes:
      - ./data-volume:/data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=0

  qgis-release-3_22-parallel-rendering:
    container_name: qgisserver-perfsuite-release-3_22-parallel-rendering
    image: qgisserver-perfsuite:release-3_22
    build:
      context: ./docker
      args:
        VERSION: release-3_22
    command: /cmd.sh
    networks:
      - qgis
      - data
    volumes:
      - ./data-volume:/data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=1
      - QGIS_SERVER_MAX_THREADS=4

  qgis-master:
    container_name: qgisserver-perfsuite-master
    image: qgisserver-perfsuite:master
    build:
      context: ./docker
      args:
        VERSION: latest
    command: /cmd.sh
    networks:
      - qgis
      - data
    volumes:
      - ./data-volume:/data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=0

  qgis-master-parallel-rendering:
    container_name: qgisserver-perfsuite-master-parallel-rendering
    image: qgisserver-perfsuite:master
    build:
      context: ./docker
      args:
        VERSION: latest
    command: /cmd.sh
    networks:
      - qgis
      - data
    volumes:
      - ./data-volume:/data
    environment:
      - QGIS_SERVER_PARALLEL_RENDERING=1
      - QGIS_SERVER_MAX_THREADS=4

  data:
    container_name: qgisserver-perfsuite-data
    image: qgisserver-perfsuite:data
    build:
      dockerfile: Dockerfile.data
      context: ./docker
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASS=root
      - POSTGRES_DBNAME=data
    ports:
      - 55432:5432
    networks:
      - data
    volumes:
      - ./data-volume:/data
      # Persist DB
      - ./data-volume/postgresql:/var/lib/postgresql

networks:
  data:
  qgis:
